### ISSUE TITLE
感觉缓存的data.db会越来越大，删除缓存数据库容量还是没变小。

### ISSUE THREAD

**Issue by wangyangaa** [px-org/PanIndex#385]
感觉缓存的data.db会越来越大，删除缓存数据库容量还是没变小。

受累请教一下有没有什么方法可以清理一下数据库无效的缓存，目前data.db有好几百兆了，低配轻量云跑起来较为吃力

**Comment by libsgh** [comment]
你可以把data.db下载下来，通过SQLite客户端查看下所有的表，哪个表数据多。
