### ISSUE TITLE
阿里云盘 文件不能下载 被识别成文件夹

### ISSUE THREAD

**Issue by 1626424216** [px-org/PanIndex#399]
![Screenshot_2023-02-22-12-27-43-552_com microsoft emmx-edit](https://user-images.githubusercontent.com/55087750/220522044-4ab73bb9-d53c-43de-a11e-431a52c520be.jpg)
![Screenshot_2023-02-22-12-27-25-865_com microsoft emmx-edit](https://user-images.githubusercontent.com/55087750/220522051-e9143d45-1f8d-4372-b265-8edb3ac65265.jpg)

**Comment by tingyue-wu** [comment]
这是没有连上阿里云盘。有没有更新到3.1.2最新版。最新版也这样那就只能等等看了。现在好像都不稳定。

**Comment by yale8888** [comment]
使用最新的3.1.2版本中，经常在下载链接时，显示为空。但网盘挂载中显示正常。遇到这个情况：需要进入后台，刷新一下缓存还是令牌才会正常。不知道这个是不是BUG。

**Comment by ilxp** [comment]
同样问题。

**Comment by libsgh** [comment]
已收到反馈，系新版签名参数到期导致，会在下版本优化

**Comment by libsgh** [comment]
已在v3.1.3版本中优化
