### ISSUE TITLE
更新3.1.2之后主页不显示文件

### ISSUE THREAD

**Issue by MUKAPP** [px-org/PanIndex#404]
挂的OneDrive，更新到3.1.2之后主页就显示空了，子目录可以正常显示
如图
![image](https://user-images.githubusercontent.com/41848070/224326499-50ad72bd-a577-4795-874f-dc68150b51ea.png)
![image](https://user-images.githubusercontent.com/41848070/224326259-544f0224-9327-4650-912c-a264c3a99efc.png)

**Comment by MUKAPP** [comment]
hhhh 竟然是404号issue

**Comment by MUKAPP** [comment]
现在哪个页面都不显示文件了，help

**Comment by MUKAPP** [comment]
只显示HEAD和README

**Comment by MUKAPP** [comment]
好了，好像是我用错版本了（（
换成amd64就可以了（（

**Comment by libsgh** [comment]
要是还未解决的话，加群讨论一下
