### ISSUE TITLE
How to get in touch regarding a security concern?

### ISSUE THREAD

**Issue by cokeBeer** [px-org/PanIndex#405]
Hello 👋

I found a potential security issue in PanIndex, how can I get in touch with you in a private way and submit my security report?

Could you add a SECURITY.md file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

**Comment by libsgh** [comment]
Hello, you can send a message to my private [email](mailto:ponbous@gmail.com).

**Comment by libsgh** [comment]
It has been fixed in version v3.1.3, many thanks

**Comment by cokeBeer** [comment]
@cokeBeer  Hi, what about publishing a [github security advisory](https://github.com/px-org/PanIndex/security/advisories)? If you feel confused about some blanks, you can add me as a collaborator on that page.

**Comment by libsgh** [comment]
> @cokeBeer Hi, what about publishing a [github security advisory](https://github.com/px-org/PanIndex/security/advisories)? If you feel confused about some blanks, you can add me as a collaborator on that page.

That's a great idea, I've added you as a collaborator.

**Comment by cokeBeer** [comment]
@libsgh Could you request a CVE id in that page before publishing the advisory? Only maintainer can do so.
