### ISSUE TITLE
我发现我的阿里云盘被限速了。123防盗链检测也比较严重

### ISSUE THREAD

**Issue by LecoLu** [px-org/PanIndex#409]
我发现我的阿里云盘被限速了。只有300kb/s的速度。而且两个月也没有被解除限速的意思。
123防盗链检测也比较严重。
目前转用天翼云，但是之前也被限速过。一般过一段时间就解除限速。

**Comment by libsgh** [comment]
阿里云盘的限速是客户端限速，123盘下载接口更新导致无法获取下载地址，可以更新下dev版本
https://docs.noki.icu/#/docs/zh/changelog
