### ISSUE TITLE
天翼云盘部分文件显示不是左对齐，感觉前面有空格

### ISSUE THREAD

**Issue by KhyHolyDragon** [px-org/PanIndex#431]
如下图，请大神赐教是什么问题？谢谢！
![image](https://github.com/px-org/PanIndex/assets/140623652/df6bf821-7cdd-40f9-b891-043469382c30)

**Comment by libsgh** [comment]
fonts cdn加载失败了，已经修复，更新dev版本

**Comment by KhyHolyDragon** [comment]
> fonts cdn加载失败了，已经修复，更新dev版本

大神，我是Docker安装的，拉取的是最新的，请问如何更新dev版本呢？谢谢！

**Comment by libsgh** [comment]
> > fonts cdn加载失败了，已经修复，更新dev版本
> 
> 大神，我是Docker安装的，拉取的是最新的，请问如何更新dev版本呢？谢谢！

用tag为dev的镜像

**Comment by KhyHolyDragon** [comment]
> > > fonts cdn加载失败了，已经修复，更新dev版本
> > 
> > 
> > 大神，我是Docker安装的，拉取的是最新的，请问如何更新dev版本呢？谢谢！
> 
> 用tag为dev的镜像

已拉取dev标签镜像，问题已解决，谢谢大神。
