### ISSUE TITLE
PanIndex Tool【获取Token】点击无反应

### ISSUE THREAD

**Issue by freemer666** [px-org/PanIndex#432]
onedrive国际版用PanIndex Tool最后获取不到Token，点击【获取Token】没有反应，修复下吧
![0QQ截图20231126164101](https://github.com/px-org/PanIndex/assets/145205140/57dabc0b-c051-453d-abd2-bb8db58fb8cb)

**Comment by libsgh** [comment]
再试试，最近给工具API换了新服务器
