### ISSUE TITLE
mdui突然出现ui错误

### ISSUE THREAD

**Issue by advancejar** [px-org/PanIndex#433]
挺喜欢mdui的，重新从本站下载后还是无法使用，
boostrap和classic都是正常的，
mdui不正常如下：
![Snipaste_2023-12-28_11-09-41](https://github.com/px-org/PanIndex/assets/58756119/6102a42f-95a6-4249-9f10-f48e91b9568d)
![Snipaste_2023-12-28_11-09-21](https://github.com/px-org/PanIndex/assets/58756119/1f09302f-a076-4263-a219-a16fe1bbc364)

都是本站5月最新版

**Comment by libsgh** [comment]
更新下3.1.5
